name: naito app CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    branches:
      - 'main'
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      
      - name: CheckOut
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Cypress run --component
        uses: cypress-io/github-action@v4.2.0
        with:
          component: true
          browser: chrome